# Exercise 110 - Shrinking your program even further

'''Add to the coin.py module, created in the previous exercises, 
a function called summary(), which shows on the screen some information 
generated by the functions that we already have in the module 
created so far.
'''
